Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/ClassVars:
  Exclude:
    - 'station.rb'
    - 'train.rb'
    - 'route.rb'
Metrics/MethodLength:
  Max: 17
Metrics/BlockLength:
  Max: 26
Metrics/AbcSize:
  Max: 27
